### ISSUE TITLE
How to configure "fix on save"

### ISSUE THREAD

**Issue by robhicks** [db-developer/fast-eslint-8#6]

**Comment by db-developer** [comment]
Thanks for asking, but to be honest: I don't use that feature, so there currently is no way to configure it.
I'll have a look at it.

**Comment by edoofx** [comment]
and no config for set 1 hotkeys for Fix All

**Comment by offaxis** [comment]
+1

**Comment by db-developer** [comment]
After having found '[Microsoft is sunsetting atom](https://github.blog/2022-06-08-sunsetting-atom/)' this weekend, I have come to the decision to not dig any further into atoms api. Instead I will move on to another editor.
However. This is Open Source and if it's important for you, you are free to fork this project and submit pull requests.
